---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
    - name: test
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test
  type: LoadBalancer
